---

- name: Create a EC2 Instance
  hosts: localhost
  gather_facts: false
  roles: 
   - ec2	

- name: Docker installation
  hosts: mygroups
  become: true
  become_user: root
  become_method: sudo
  roles:
    - docker
